### PR TITLE
collapsible sidebar, download functionality, css

### PR DESCRIPTION
**Pull request by willdebras**
Hi Gene-- 

Nice to see you again. Here is my work from Saturday.

Some things I did/worked on:

1. Adding a download button to save the leaflet map the user generates as a .png.
2. Adding a semi-collapsible sidebar where one could add drop downs for additional data filters without cluttering the space. This can be adjusted in .ui and style.css.
3. Adding some css to make the text and ui elements collapse in the sidebar and to change the opacity of the absolutePanel
4. Putting the whole ui in a dashboardBody from shinydashboard

Other things I talked about with others at the event that I think would be interesting:

The ability to download a report with a lot of different metrics for either a. an area located on the map or b. an individual neighborhood, so that activists could send things to their alderman to pressure for policy. The map download button was a bit of a start at this idea.

A well style UI layout with lots of different interact-able widgets.

In the next week or so, I'd love to send some examples of shiny UI layouts as you, Chase, and I talked about Saturday. I'm happy to help work on this tool to any degree you're welcoming outside hands.

Cheers,
Will

### CODE REVIEW

**Comment by geneorama** [comment]
@willdebras I think that's a great idea about being able to subset by geography, such as ward or community area.  I think we should create an issue for that.

**Comment by geneorama** [comment]
Will, I'm wondering how we can move the existing filtering and proposed geography filtering to the menu on the left that you created.

**Comment by willdebras** [comment]
In server side, this is just stored in a `menuItem()`. I think it could easily be an input with a reference to an inputId(). For example I have a downloadButton() in there, but this could be any radio button or any other input as well. I'll have to take a look later this week and try to implement and PR back to this branch.

**Comment by willdebras** [comment]
Can even add an easing function in CSS so the open and close is a little cleaner.

**Pull request merged**
